apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tuluat-portal-ingress
  namespace: tuluat-system
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: portal.tuluat.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tuluat-operator-service
                port:
                  number: 8080
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: tuluat-operator-service
                port:
                  number: 8080
