FROM eclipse-temurin:25-jre
WORKDIR /app

RUN groupadd -r appgroup && useradd -r -g appgroup appuser

COPY tuluat-app/target/tuluat-app-1.0.0-SNAPSHOT.jar app.jar
RUN chown -R appuser:appgroup /app

USER appuser

EXPOSE 8080

ENTRYPOINT ["java", "--enable-preview", "-Dspring.threads.virtual.enabled=true", "-jar", "app.jar"]
