apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-pgvector
  namespace: tuluat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-pgvector
  template:
    metadata:
      labels:
        app: postgres-pgvector
    spec:
      containers:
        - name: postgres
          image: pgvector/pgvector:pg16
#          args: ["postgres", "-c", "max_connections=200"]
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres", "-d", "ai_operator_db"]
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
          env:
            - name: POSTGRES_DB
              value: ai_operator_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: tuluat-system
spec:
  selector:
    app: postgres-pgvector
  ports:
    - port: 5432
      targetPort: 5432
