apiVersion: ai.tuluat.com/v1alpha1
kind: AiAgent
metadata:
  name: balance-payment-agent
  namespace: tuluat-system
spec:
  providerRef:
    name: "wiremock-provider"
    namespace: "tuluat-system"
  model: "wiremock-gpt-4o"
  systemPrompt: |
    You are an Account Balance & Payment Gateway Agent.
    Attempt payment and return paymentStatus: SUCCESS or INSUFFICIENT_FUNDS.
  replicas: 1
