apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  namespace: tuluat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-server
  template:
    metadata:
      labels:
        app: temporal-server
    spec:
      containers:
        - name: temporal-server
          image: temporalio/auto-setup:1.23.0
          env:
            - name: DB
              value: postgresql
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_SEEDS
              value: postgres-service
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PWD
              value: postgres
          ports:
            - containerPort: 7233
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-service
  namespace: tuluat-system
spec:
  selector:
    app: temporal-server
  ports:
    - name: grpc
      port: 7233
      targetPort: 7233
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-ui
  namespace: tuluat-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-ui
  template:
    metadata:
      labels:
        app: temporal-ui
    spec:
      containers:
        - name: temporal-ui
          image: temporalio/ui:2.27.0
          env:
            - name: TEMPORAL_ADDRESS
              value: temporal-service:7233
            - name: TEMPORAL_CORS_ORIGINS
              value: "http://localhost:8233"
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-ui-service
  namespace: tuluat-system
spec:
  selector:
    app: temporal-ui
  ports:
    - name: http
      port: 8233
      targetPort: 8080
