{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.namespace.name }}
    app.kubernetes.io/part-of: tuluat-operator
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}
